version: "3.3"
services:
  test_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POETRY_VIRTUALENVS_PATH: /poetry
      POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      METRO_NEWS_URL: https://mosday.ru/news/tags.php?metro
    ports:
      - 8080:8080/tcp
    volumes:
      - ./src:/test_api/src:ro
      - ./pyproject.toml:/test_api/pyproject.toml:ro
      - ./poetry.lock:/test_api/poetry.lock:ro
    command: server
    restart: always
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp